import Footer from "@/components/core/Footer";
import NavbarWrapper from "@/components/core/NavbarWrapper";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import SafeHydrate from "./hydrate";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans antialiased`}>
        <SafeHydrate>
          <NavbarWrapper />
          {children}
          <Footer />
        </SafeHydrate>
      </body>
    </html>
  );
}
